spring:
  application:
    name: taskmanager

  datasource:
    url: jdbc:postgresql://localhost:5432/taskmanager
    username: postgres
    password: root123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

app:
  jwt:
    secret: your-very-long-secret-key-at-least-32-characters
    expiration-ms: 86400000

  cors:
    allowed-origins: http://localhost:5173,http://localhost:3000


  gemini:
    model: gemini-3.8-flash